# Generated by Django 5.2.4 on 2025-08-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='academic_content/')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('RESEARCH_PAPER', 'Research Paper'), ('THESIS', 'Thesis'), ('JOURNAL', 'Journal')], max_length=50)),
                ('extracted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
