# Generated by Django 5.2.4 on 2025-08-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='academic_content/')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('introduction', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('RESEARCH_PAPER', 'Research Paper'), ('THESIS', 'Thesis'), ('JOURNAL', 'Journal')], max_length=50)),
                ('extracted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicContent',
        ),
    ]
