# Generated by Django 5.2.4 on 2025-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_researchpaper_delete_academiccontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='extracted_date',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='results',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='algorithms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='author',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='file',
            field=models.FileField(upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
