# Generated by Django 5.2.4 on 2025-08-02 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0003_remove_researchpaper_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
