# Generated by Django 5.2.4 on 2025-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0004_researchpaper_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchpaper',
            old_name='algorithms',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='researchpaper',
            old_name='content',
            new_name='conclusion',
        ),
        migrations.RenameField(
            model_name='researchpaper',
            old_name='uploaded_at',
            new_name='extracted_date',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='author',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='content_type',
            field=models.CharField(choices=[('RESEARCH_PAPER', 'Research Paper'), ('THESIS', 'Thesis'), ('JOURNAL', 'Journal')], default='RESEARCH_PAPER', max_length=50),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='methodology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='file',
            field=models.FileField(upload_to='academic_content/'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
